"""Migração inicial

Revision ID: 29830d3ac82c
Revises: 
Create Date: 2025-07-12 14:03:41.290218

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '29830d3ac82c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('log_atualizacao_tarefa')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log_atualizacao_tarefa',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('tarefa_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('status_anterior_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('status_novo_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('data_hora', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['tarefa_id'], ['lista.id'], name=op.f('log_atualizacao_tarefa_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
