"""Recriar tabela log_atualizacao_tarefa

Revision ID: 4f4b6c5e641f
Revises: 29830d3ac82c
Create Date: 2025-07-12 14:22:02.166207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f4b6c5e641f'
down_revision = '29830d3ac82c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log_atualizacao_tarefa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tarefa_id', sa.Integer(), nullable=False),
    sa.Column('status_anterior_id', sa.Integer(), nullable=True),
    sa.Column('status_novo_id', sa.Integer(), nullable=True),
    sa.Column('data_hora', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tarefa_id'], ['lista.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('log_atualizacao_tarefa')
    # ### end Alembic commands ###
